name: Implantar no Heroku

on:
  push:
    branches:
      - master

jobs:
  implantar:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Implantar no Heroku
      uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: "nome-do-seu-app"
        heroku_email: "seu-email@example.com"