name: Implantar no AWS # nome do workspace

on: # Define o trigger (gatilho) que dará o start da pipeline
  push: # O trigger será o push
    branches:  # somente para a branch master
    - master

jobs:
  implantar:
    runs-on: ubuntu-latest # provisiona uma máquina, no caso uma máquina ubuntu sendo a sua última versão LTS

    steps:
    - name: Fazer checkout do código
      uses: actions/checkout@v2 # permite fazer o checkout (clonar) de um repositório em um ambiente de execução. Ela é utilizada para garantir que o código-fonte do repositório esteja disponível para as etapas subsequentes do fluxo de trabalho.

    - name: Configurar credenciais da AWS
      uses: aws-actions/configure-aws-credentials@v1 # action que configura as credenciais da aws
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }} # Id da chave de acesso da AWS
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} # Chave de acesso
        aws-region: us-west-2 # A região aonde a aplicação rodará

    - name: Implantar no AWS
      run: |
        aws s3 sync . s3://meu-bucket
      # aws s3 sync -> comando da AWS CLI usado para sincronizar diretórios e objetos entre o sistema de arquivos local e um bucket do S3, ou entre dois buckets do S3
      # . -> Especifica que deseja sincronizar o diretório local
      # s3://meu-bucket -> especifica o bucket do s3 para onde os arquivos irão