name: Implantar no Heroku # nome do workspace

on: # Define o trigger (gatilho) que dará o start da pipeline
  push: # O trigger será o push
    branches: # somente para a branch master
      - master

jobs: 
  implantar:
    runs-on: ubuntu-latest # provisiona uma máquina, no caso uma máquina ubuntu sendo a sua última versão LTS

    steps:
    - uses: actions/checkout@v2 # permite fazer o checkout (clonar) de um repositório em um ambiente de execução. Ela é utilizada para garantir que o código-fonte do repositório esteja disponível para as etapas subsequentes do fluxo de trabalho.

    - name: Implantar no Heroku
      uses: akhileshns/heroku-deploy@v3.12.12 # action que é responsável por fazer a automatização do processo de implamentação do heroku
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}} # usado para autenticar no heroku achando as configurações da conta utilizada
        heroku_app_name: "nome-do-seu-app" # Nome da aplicação que será feito o deploy/update
        heroku_email: "seu-email@example.com" # Email usado no heroku