name: Aplicação Python

on: [push]

jobs:
  construir:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Configurar Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Testar com pytest
      run: |
        pytest